package com.rudolfschmidt.majara.v2.tokens;

public enum Types {
	ATTRIBUTE_KEY, ATTRIBUTE_TEXT_VALUE, ELEMENT_TEXT_VALUE, ATTRIBUTES_START, ATTRIBUTES_END, DOCTYPE, PIPE, COMMENT, INCLUDE, EXTENDS, BLOCK, APPEND, ELEMENT_MODEL_VALUE, ATTRIBUTE_MODEL_VALUE, CODE_IF, CODE_ELSE, CODE_EACH, ELEMENT_NAME
}
